### ISSUE TITLE
Using bigger environment

### ISSUE THREAD

**Issue by Juliaa-dantas** [pouyan-asg/Q-Learning-based-Navigation-with-Sending-a-Sequence-of-Goals#1]
Hi,
I want to use your codes for a bigger environment, two quick questions:
- how much can I increase the environment? 
- is it possible to not use a fix reward? I want to consider bigger penalty for obstacles that are located in longer distances

thanks

**Comment by pouyan-asg** [comment]
Hi,

you can use my codes for bigger environment but consider that for Q-learning you should have info about obstacles. Also, reward can be any number or a formula of distance.

**Comment by Juliaa-dantas** [comment]
Thanks
